################################################################
#
#
# Pipeline pipeline_atacseq.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

# Temporal directory to use. Sometimes /scratch is full and is better to
# use an alternative
general_temporal_dir: /fastdata/mb1ims/tmp

########################################################
# the genome to use (UCSC convention)
genome: hg38_noalt

genome_dir: /shared/sudlab1/General/mirror/genomes/index

################################################################
#
# Location of annotation database
#
################################################################
geneset: /shared/sudlab1/General/annotations/hg38_noalt_ensembl85/ensembl.dir/geneset_all.gtf.gz


    ################################################################
    #
    # samples details
    #
    #
    ################################################################
samples:

    # Tab separated table with:
    #        Sample_name    condition(control/treatment)    five_prime_quality_trimming(number of base pairs trimmed from both reads' 5' end in a pair)
    #        nd2345    control    2
    #
    # Has to specify all the samples in the base directory with the details!
    details_table: samples.tsv

    ################################################################
    #
    # filtering options
    #
    ################################################################
filtering:

    # Removes peaks which have any overlap with the specified bed areas
    # These can be for example areas of low mappability or hotspots 
    # (areas of excessively high mappability)
    # Bed file list separated by ,
    bed_exclusions: [/shared/sudlab1/General/projects/segmentation/chromHMM_excluded_regions/hg38_ENCODE_excluded_regions_liftup_from_hg19.bed,/shared/sudlab1/General/projects/segmentation/chromHMM_excluded_regions/hg38_ENCODE_excluded_high_mappability_regions.bed.gz]

   
    # Number of multimapping proper pairs not allowed to proceed the filtering.
    # Eg. If allowed_multimapper_proper_pairs=3 = 6 single mappings
    # Any reads which have the same or more than these mappings will be filtered out.
    # 2 means only allow single mapping pairs
    allowed_multimapper_proper_pairs: 2


    # contigs to remove before peak calling separated by |
    # For ATAC-seq probably want to remove chrM
    # Does partial matching: for each element *element* is removed
    contigs_to_remove: _alt|_hap|chrM|_random|chrUn


 
    ################################################################
    #
    # End extending
    #
    ################################################################
end_extending:

    # Shift to apply to the 5' end of the reads to displace them.
    # Only negative numbers implemented 
    # (negative number will shift it upstream)
    # If nothing is specified, it defaults to -100
    shift: -100

    # Extension size to apply to the 5' ends of the reads after shifting
    # This will make them longer. Only positive numbers implemented
    # Positive number extends downstream
    # If nothing is specified, it defaults to 200
    extsize: 200



    ################################################################
    #
    # MACS2
    #
    ################################################################
macs2:

    # The macs2 thresholding method used, at the moment either:
    # q
    # p
    # (q-value or p-value)
    # If nothing is specified, it defaults to "p"
    threshold_method: q

    # The thresholding quantity for the threshold_method specified
    # If nothing is specified, it defaults to 0.01
    threshold_quantity: 0.01




    ################################################################
    #
    # RNAseq options
    # 
    ################################################################
salmon:
   threads: 4
   memory: 4G

stringtie:
   threads: 4
   memory: 2G
   merge_threads: 8
    ################################################################
    #
    # sphinxreport build options
    #
    ################################################################
report:

    # prefix to use for publishing the report from this pipeline
    prefix: default

